version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements_test.txt
          pkg-manager: pip
      - run:
          command: tox
          name: Test


workflows:
  main:
    jobs:
      - build-and-test:
          context: p24
